<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Override;

final class Version20241021134554 extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return 'Новости';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
    }

    #[Override]
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE news');
    }
}
